language: elixir
otp_release:
  - 18.0
  - 18.1
  - 18.2
elixir:
  - 1.2.0
  - 1.2.1
  - 1.2.2
  - 1.1.1
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get --only test
script:
  - MIX_ENV=test mix dialyzer.plt
after_script:
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
  - /home/travis/bin/artifacts upload --key $ARTIFACTS_KEY --secret $ARTIFACTS_SECRET --bucket $ARTIFACTS_BUCKET --target-paths travis_elixir_plts plts
